Repository opendatahub-io/vllm, pull requests merged in 2024-10, with the labels that each got.

#176 bump tgis adapter to v0.5.1
  Dockerfile.rocm.ubi
  Dockerfile.ubi
Labels: approved

#165 [core][distributed] fix zmq hang (#6759)
  vllm/distributed/device_communicators/shm_broadcast.py
Labels: lgtm

#179 Retrigger build
  Dockerfile.rocm.ubi
Labels: ok-to-test, lgtm, approved

#204 Dockerfile*.ubi: install vllm and vllm-tgis-adapter in the same step to make sure the correct version is installed
  Dockerfile.rocm.ubi
  Dockerfile.ubi
Labels: lgtm, approved

#203 Dockerfile.hpu: downgrade vllm-tgis-adapter to a compatible version
  Dockerfile.hpu.ubi
Labels: ok-to-test, lgtm, approved
