Repository opendatahub-io/vllm, pull requests merged in 2024-08, with the labels that each got.

#117 [Cherry-Pick] [Bugfix] Set SamplingParams.max_tokens for OpenAI requests if not provided by user (#6954)
  tests/entrypoints/openai/test_completion.py
  tests/entrypoints/openai/test_serving_chat.py
  vllm/entrypoints/openai/logits_processors.py
  vllm/entrypoints/openai/protocol.py
  vllm/entrypoints/openai/serving_chat.py
  vllm/entrypoints/openai/serving_completion.py
  vllm/entrypoints/openai/serving_engine.py
Labels: lgtm, approved

#122 Dockerfile.ubi: add missing dependency
  Dockerfile.ubi
Labels: lgtm, approved

#127 fix build for 0.5.4
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#125 Allow long max seq length by default
  Dockerfile.ubi
Labels: ok-to-test

#128 smoke test: kill server on timeout
  extras/smoke-test.sh
Labels: approved

#131 fix: enable logprobs during spec decoding by default
  Dockerfile.ubi
Labels: ok-to-test, approved

#132 deps: bump vllm-tgis-adapter to 0.4.0
  Dockerfile.ubi
Labels: lgtm, approved
