Repository opendatahub-io/vllm, pull requests merged in 2024-06, with the labels that each got.

#43 chore(deps): update dependencies to squash snyk reported issues.
  requirements-common.txt
Labels: lgtm, approved

#44 chore(deps): update dependencies to squash snyk reported issues.
  requirements-common.txt
Labels: approved

#45 gha: add sync workflow
  .github/workflows/sync-with-upstream.yml
Labels: lgtm, approved

#48 Dockerfile.ubi: use distributed-executor-backend=mp as default
  Dockerfile.ubi
Labels: lgtm, approved

#51 Dockerfile.ubi: remove vllm-nccl workaround
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#53 dockerfile improvements
  Dockerfile.ubi
Labels: lgtm, approved, do-not-merge/hold

#56 Dockerfile.ubi: add missing requirements-*.txt bind mounts
  Dockerfile.ubi
Labels: ok-to-test, approved

#55 add triton CustomCacheManager
  Dockerfile.ubi
  extras/custom_cache_manager.py
Labels: ok-to-test, approved

#58 gha: sync-with-upstream workflow create PRs as draft
  .github/workflows/sync-with-upstream.yml
Labels: approved

#59 add smoke/unit tests scripts
  extras/smoke-test.sh
  extras/unit-tests.sh
Labels: approved

#60 extras: exit unit tests on err
  extras/unit-tests.sh
Labels: approved

#61 Dockerfile.ubi: misc improvements
  Dockerfile.ubi
Labels: ok-to-test, approved

#64 Dockerfile.ubi: use tensorizer
  Dockerfile.ubi
Labels: ok-to-test, lgtm

#66 Dockerfile.ubi: pin vllm-tgis-adapter to 0.1.2
  Dockerfile.ubi
Labels: lgtm, approved

#67 sync release with main
  Dockerfile.ubi
Labels: lgtm, approved
