Repository opendatahub-io/vllm, pull requests merged in 2024-07, with the labels that each got.

#77 gha: fix fetch step in upstream sync workflow
  .github/workflows/sync-with-upstream.yml
Labels: approved

#78 gha: have sync workflow always update PR body
  .github/workflows/sync-with-upstream.yml
Labels: approved

#79 Dockerfile.ubi: bump vllm-tgis-adapter to 0.1.3
  Dockerfile.ubi
Labels: lgtm, approved

#80 sync release with main
  .github/workflows/sync-with-upstream.yml
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#87 Dockerfile.ubi: get rid of --distributed-executor-backend=mp
  Dockerfile.ubi
Labels: ok-to-test, approved

#85 Dockerfile.ubi: add flashinfer
  Dockerfile.ubi
Labels: ok-to-test, approved

#90 pin adapter to 0.2.0
  Dockerfile.ubi
Labels: lgtm, approved

#91 deps: bump flashinfer to 0.0.9
  Dockerfile.ubi
Labels: approved

#93 Dockerfile.ubi: updates for 0.5.2
  .github/workflows/reminder_comment.yml
  Dockerfile.ubi
Labels: ok-to-test, approved, ready

#89 Update OWNERS with IBM folks
  OWNERS
Labels: lgtm, approved, ready

#96 gha: remove reminder_comment workflow
  OWNERS
Labels: approved

#95 [CI/Build] fix: update setup.py to differentiate between fork and upstream
  setup.py
Labels: ok-to-test, lgtm, approved

#97 Dockerfile.ubi: properly mount .git dir
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#98 Revert "[CI/Build] fix: update setup.py to differentiate between fork and upstream"
  setup.py
Labels: approved

#99 Dockerfile.ubi: bump vllm-tgis-adapter to 0.2.2
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved, ready

#100 [CI/Build] fix: update setup.py to differentiate between main and instructlab
  setup.py
Labels: needs-ok-to-test

#109 deps: bump vllm-tgis-adapter to 0.2.3
  Dockerfile.ubi
Labels: approved

#108 Dockerfile.ubi: get rid of custom cache manager
  Dockerfile.ubi
  extras/custom_cache_manager.py
Labels: approved
