Repository opendatahub-io/vllm, pull requests merged in 2024-05, with the labels that each got.

#14 dockerfile cleanup
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#17 fix stats
  vllm/tgis_utils/metrics.py
Labels: ok-to-test, lgtm, approved

#23 Dockerfile: use fixed vllm-provided nccl version
  Dockerfile.ubi
Labels: lgtm, approved

#24 bump ubi base image tag
  Dockerfile.ubi
Labels: lgtm, approved

#25 Ibm main update 2024-05-16
  Dockerfile.ubi
  vllm/tgis_utils/metrics.py
Labels: approved

#30 Dockerfile.ubi: get rid of prebuilt-wheel stage
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#31 Docker.ubi: add missing package git
  Dockerfile.ubi
Labels: lgtm, approved

#34 [CI/Build] use existing shadow-utils in Dockerfile.ubi
  Dockerfile.ubi
Labels: ok-to-test, lgtm, approved

#36 grpc_server: fix tokenizer group usage
  vllm/entrypoints/grpc/grpc_server.py
Labels: ok-to-test, lgtm, approved

#37 grpc_server: fix tokenizer group usage
  vllm/entrypoints/grpc/grpc_server.py
Labels: approved

#40 deps: get rid of duplicated fastapi entry
  requirements-common.txt
Labels: approved

#27 add ubi dockerfile
  Dockerfile.ubi
Labels: lgtm, approved
