Repository opendatahub-io/vllm, pull requests merged in 2025-03, with the labels that each got.

#348 deps: bump vllm-tgis-adapter to 0.6.3
  Dockerfile.rocm.ubi
  Dockerfile.ubi
Labels: approved

#349 adding support for s390x
  Dockerfile.s390x
  cmake/cpu_extension.cmake
  csrc/cpu/attention.cpp
  csrc/cpu/cpu_types.hpp
  csrc/cpu/cpu_types_vxe.hpp
  csrc/cpu/quant.cpp
  requirements-cpu.txt
Labels: needs-ok-to-test, approved, do-not-merge/hold

#352 fix: add gcc-gfortran package to dependency list
  Dockerfile.s390x.ubi
Labels: needs-ok-to-test, approved

#350 Dockerfile.rocm.ubi: bump ROCm to 6.3.4
  Dockerfile.rocm.ubi
Labels: approved

#342 UBI9 based Dockerfile for IBM ppc64le
  Dockerfile.ppc64le.ubi
  requirements-common.txt
  requirements-cuda.txt
  requirements-rocm.txt
Labels: needs-ok-to-test, approved, do-not-merge/hold

#355 Dockerfile.s390x: fix dependency build in vllm-tgis-adapter install
  Dockerfile.ppc64le.ubi
  Dockerfile.s390x.ubi
Labels: needs-ok-to-test, approved

#356 update: building numactl and lapack from source
  Dockerfile.ppc64le.ubi
Labels: needs-ok-to-test, approved

#357 fix: fixed rust env variables and install perl-core dependency
  Dockerfile.s390x.ubi
Labels: needs-ok-to-test, approved

#368 Dockerfile.rocm.ubi: add [audio,video,tensorizer] extras to vllm install
  Dockerfile.rocm.ubi
Labels: approved

#371 Dockerfile.ppc64le.ubi: retry openblas install on failure, pin cmake<4
  Dockerfile.ppc64le.ubi
Labels: needs-ok-to-test
